name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: 'temurin'
      - name: Build with Maven
        run: ./mvnw --batch-mode verify
